# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C:/Users/vico/AppData/Roaming/.olauncher/olruntime/windows-x64/java-runtime-epsilon/runtime

# Fabric Properties
minecraft_version=26.1-snapshot-10
loader_version=0.18.4
loom_version=1.16.0-alpha.10

# Fabric API
fabric_version=0.143.7+26.1

# Mod Properties
mod_version=1.0.2
maven_group=net.crioch
archives_base_name=fluid_sieve
