# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.1.1
minecraft_dependency_version=~26.1
loader_version=0.18.6
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_version=0.145.2+26.1.1

# Mod Properties
mod_version=1.0.5
maven_group=net.crioch
archives_base_name=fluid_sieve
