# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.1-pre-2
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_version=0.143.14+26.1

# Mod Properties
mod_version=1.0.4
maven_group=net.crioch
archives_base_name=fluid_sieve
